# Generated by Django 5.2.6 on 2026-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_diem', models.CharField(max_length=50)),
                ('ph', models.FloatField()),
                ('do', models.FloatField()),
                ('bod5', models.FloatField()),
                ('cod', models.FloatField()),
                ('nh4', models.FloatField()),
                ('coliform', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
